# Generated by Django 2.2.2 on 2019-06-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='in_bad_condition',
            field=models.BooleanField(default=False),
        ),
    ]
